# Generated by Django 5.1.2 on 2024-11-01 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='service/item/hero')),
                ('lead_image_1', models.ImageField(blank=True, null=True, upload_to='service/item/lead')),
                ('lead_image_2', models.ImageField(blank=True, null=True, upload_to='service/item/lead')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='service/item/banner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Item',
                'verbose_name_plural': 'Service Items',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/icons')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServiceItemCategory',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='service/item/category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='portal.serviceitem')),
            ],
            options={
                'verbose_name': 'Service Item Category',
                'verbose_name_plural': 'Service Item Categories',
            },
        ),
        migrations.CreateModel(
            name='ServiceItemOption',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='service/item/option')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='portal.serviceitemcategory')),
            ],
            options={
                'verbose_name': 'Service Item Option',
                'verbose_name_plural': 'Service Item Options',
            },
        ),
        migrations.CreateModel(
            name='ServiceItemOptionDescription',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('language', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_item_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='portal.serviceitemoption')),
            ],
            options={
                'verbose_name': 'Service Item Option Description',
                'verbose_name_plural': 'Service Item Option Descriptions',
            },
        ),
        migrations.CreateModel(
            name='ServiceItemOptionDescriptionValues',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(max_length=50)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_item_option_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_values', to='portal.serviceitemoptiondescription')),
            ],
            options={
                'verbose_name': 'Service Item Option Description Value',
                'verbose_name_plural': 'Service Item Option Description Values',
            },
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.services'),
        ),
    ]
